apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-ui
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-vote
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/mikimoyal/vote-ui.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
